export const ENQUIRY_PRODUCTS = "ENQUIRY_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SET_CATGORY_ID = "SET_CATGORY_ID";
// export const REMOVE_TO_ENQUIRY_PRODUCTS = "REMOVE_TO_ENQUIRY_PRODUCTS";